- name: add gnupg
  package: name="gnupg" state=present

- name: add key
  apt_key: url="https://www.postgresql.org/media/keys/ACCC4CF8.asc" state=present

- name: add repo
  apt_repository: repo="deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main"

